# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:w4S++UiIxNfDVW1tCt2NDlAy/wlXkMH1tKIMbevnV5o=,iv:ykS7xTJgknbZiWgkVqpFozmjigfVLH1r1ZbNhMf0hkc=,tag:qGXMDK8y+WLP1xTKqGDyeQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l5pn0rt2p69q09asv9nf2vew4tamcxhqstxrg6wv9z79nglr8p0qtcnxrq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTCtuNXVBOTRodHVUUDQ1
        N0xzY2hmVkp6bFJ1cnJjTUJlQ3VjcVNEdHpFCmFaa0NsbE1GNklSdFVOUCtsdlht
        N25tWjRlVjY2bGxMd21xazJRd25Wa28KLS0tIDhuNTNKRWVKbWdZWWRsRDUva2Vl
        L1YyVkVobVBXSHpWZnRaSjFNdXRKbjQKWy0Np99QYDxKDSE5wvxRbVwAy/g/jbmz
        LdAea3qcGtpbK0rA0291Rn18T/R6cJrp4YxJJ6/HgmDr0n/AmjEcYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T04:11:25Z"
  mac: ENC[AES256_GCM,data:GNjPUu6Aa236+5C2sNa+Ae0ww8b6DCAEIzvTRbfO542rHFOtQDu4lZnUylJYMeye7w+jB15C+GM4acllcDWIQXyyJt+SeE4xGG2dlc+XT9Uw62cYNEmiwAx2GKjqCyA/1ch1VkFBb49w0lYDYNoeYpCtlhnyqE7n7WzwbE182kU=,iv:Pivufcb26IRw5UKt4r53NZHA+lXpaeDzTWGFXDRap5c=,tag:o+dUTNdJcXuuLZ78NkUelw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
