# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JMmJSpTMHz4gAqHLqaIsPj7UhgjG8zUEH0oofRbn2XqSoG1KDr7azw==,iv:wki0W9eqoT/uqKUzqPpJeS3KzL98JUVkXV/wZd3JNDU=,tag:Y/3ynCWePtdq5I5QDKzGNg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l5pn0rt2p69q09asv9nf2vew4tamcxhqstxrg6wv9z79nglr8p0qtcnxrq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzlTcEFCQytXNTNlV0xZ
        azhEbkxWRGxvRndvM3JMb3hqRVExTTE4QlhRCk5JcE9MM3hTckp6cFlmWUlzQ0ZR
        OGdhSWQ5cDVWYnRubWE3elJicWJRRzQKLS0tIEdrVitUQytueWt6T2phOVBpV2dV
        L1lpYXlxV1B2Z21SZHdsa2gvY2ZzQmsKBLlKuXIXFZUo9te2aphMa9CNWUNMs3K5
        i/DfkuVnLWjqUKpZqnQEH+iPSVVQW/d71QhKx/cyS5JR+OQJdiFu4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T03:09:00Z"
  mac: ENC[AES256_GCM,data:HdEtaR1eQrRmgu6cr2FGkmrgNmW3ToAFtSVKxIKTSB8ICSQ3dkVAadtzjApnzUpTfdkH0zYfgIG0HaSuPpxf03TvVWE9jOzNsGh4HSSpdn9E3t9XeXkWjAMXAvglhKBE+L7f/2l41UltAQ+8NF2R9F/ivkoy8suupku9dEg4n+g=,iv:tXtiiFLeIofiYr43xAeh5nU4pOUAChZs8oYGCi6y8YU=,tag:nOIfAucFdBLwisoERUsuuA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
