apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Q7uY20KSAEnRmSrYyqw=,iv:9Eau7qmimYhtjzyfbEaXwhJPG0XZbZ+g9mwCD8p1G90=,tag:3+XWQqmuQ8svGcRrQVCs7A==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:S8CRdMaPo62w7+mJXSlW2batjrRm3R+2bI9caB4FnCtxUqe+,iv:xJL4fGKQjxzWGos2GkEa5juq3rYOj4prtoZlM6S4eXA=,tag:vIhN20vXtEMen7ZBfhTL/Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l5pn0rt2p69q09asv9nf2vew4tamcxhqstxrg6wv9z79nglr8p0qtcnxrq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc2QwbkJta3hHSVQzWDZ3
        TkFqdDRQZENIcWQ1aDd3Tk1hWWJKOTNkSUFZCkd1bDM0WlBjQjE2cG1OeGxlSGth
        TmhEUUk4eG1lOU11MzErcHhFRDM4QkkKLS0tIFpSRTJFVGRBQ0U0Rll5SDBOanRi
        OUNwMDk3V05DaldsNk9DaFBZNFdhSzAKLLrbNYOI7W/+SwnR5dFoMKGgm4e3r9I9
        WB19v6Q9EfrZUZT3fATRNsAtxgb3+IcOgspJbfxlkmCx+Rf1YmR3mA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T04:11:25Z"
  mac: ENC[AES256_GCM,data:zw1zlUhekM7Ol2LR9QyPsh5R3i0RuOvoKl9EP2bYeIk7RRxGOVTXiougY2g+T51dWS2kNjbNfZx3TFw9CjoHiMekVVSjkLT/HMcMXTs2E4i+2XzoSWc9D9xpDC+pBlkkvgJDy5mWB2NaQzrYTHFtOGEsfnAYA26ayeTHt0UYH5g=,iv:iYdXTm6v2vTMij8mUtkBHMiAHfdQlwzAoYYHS6yh88c=,tag:c9sGg875dHvh2vbqXPP0sQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
