apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yGYfVB5U6sN2HB8Xh0M=,iv:BuaVcq07rZM6WD/4KHVzH+7U6igFl8tkNe5lqyZEfD8=,tag:P5vmw5G2GV1RGsnRolkERw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:O1SoL5sIMWrnYg0COXm/oxbmSuu2qupGGhawo6bBBzUhHFnD,iv:d+q/CPCd7STkdXpMGoDB/Hy6air+TxgNHonITvruoF4=,tag:PPPkISZbL+/Iyy+t3jAbyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l5pn0rt2p69q09asv9nf2vew4tamcxhqstxrg6wv9z79nglr8p0qtcnxrq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaTBUMEtFUmZIYjNiZXNq
        UkR5ZnQ5aFJzdm1PaTMzZHl2RllSQjkrT1hrCjFCR3Nqam92UlpWQWVuT0d3d1BO
        V0pWMXB4SzBnNXIvcFVtWUxaL01BZ0UKLS0tIGgwZ0taTEloVHR0dXM3QVhPU05J
        OExSb0NxSXJHcjhnbU9yUGgzVmR0ZzgK3xDoWIXSnQxLIViiTBi4AsaN+hxhcJf1
        4kdx9rQ60wTS75nnHMRcGdLfsbD9uugo/nPyXFTDAFFfKVKZueJjCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T04:33:45Z"
  mac: ENC[AES256_GCM,data:5LF2px6N0fN7Z98PGqQprt89veAiIl/i0TjpnskLcxaBXMr64ew9RtyL7ofX17nEtI5Y/3d+M/JE+xvKwC+nn5zoQgvamHyhX3k1lQtkshuC1J5Vz3ngqjbXmeCwIb2bufZA2a8fovhZs0x56zwLuCLDwqaDKYUR6+x5Pj2wK6k=,iv:5+dqGQ47wZ0QyEg7vPnoeHbkIOwSp2xxTRxDf8vlfd8=,tag:zQIY/px2lteQEvWgFe4CdQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
