apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:QM/ynPNdxm06AjcJTutSHGJ/F5oP8NSIpVc9Hd4ncctS54MDtJSqiHH2+LE09Sc/tDHKtTuRaEmfSlUBxKPGufUNdzHDIT6yXGTb,iv:ZWlZhgPIAHrsRPyh8nwltopWnf9eg7aSaYTYg7V/dHk=,tag:HKw1I+TpVUR/K0yosquCVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l5pn0rt2p69q09asv9nf2vew4tamcxhqstxrg6wv9z79nglr8p0qtcnxrq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSlBXVzR5dUlkZHRkS3lZ
        QU5kZncrOC8rY1JTZUlKTHFvcy9Pa1RxaDJBClZUSTV3RFdFSUhSUXlaSUI0U1V6
        TkV5djFSVnpTYXdmTnljQWx4cGRTV3MKLS0tIExUbkk5MnYvSi9KWWh2cHVXOW9H
        eTIxSG55eE1tcEpJVm0wL3RiK3ZuSEEKsHQItPc8wWuFuHGK3cKkXrwHt+d5gn2c
        75eElTise/UUWeoQ2QdpUdWf2m50cpRhfy5ZtiXabeybMbiEP6/PyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T15:05:45Z"
  mac: ENC[AES256_GCM,data:A5AyWTq5Nytlp0M6OPQBxHCtdJdyhNhWi3zsHxKtv14hr7Q8A1m+LhgzhdcROI80EM7Gg/IcQ7AXmCU3bL66pdYVIwxaKewgWlIx644mgX1wSvv05pc6/3/7IaHvTloPovXew+om5c4K7UdZOse8Fy0jXd882ALZOEBVLdwuRoU=,iv:INKg9cj1TLS1PwvlD8FTQVGLYvTuKKNyypan1Sg42p4=,tag:U+BdM87+HBdfR9hK6hPwog==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
