apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:XLLgUAwe9WZBq8NAM+yNKeD8ZV38dZDLSf+v+vSTpsl7gYd1b5VcUZXusT28wvdqSYByBzQ6F/bNt73ZWoM3//vS1fJZSXmdEY7A,iv:/c/BYAnuvCQAEqam0IVhOO4h9VS+td2il1qYKGAjxUE=,tag:mMv8ZgyhGJS0XtdHRXDVjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l5pn0rt2p69q09asv9nf2vew4tamcxhqstxrg6wv9z79nglr8p0qtcnxrq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNDdkMVdka3hRVktlcmN5
        MFNlMmQvL1A2MWlFM1RldEVlTkI0YmV0QkE4Ck5GdXhWUStjcmoxZk84cHFiUVhx
        eEJ4YUxyRmVXVEgzckVCaUJWLzUvem8KLS0tIHBBZkpDWS8rdmRWWDBlZDJNZnpT
        Nzd6ZG5VMmVaNW1kMzl4STdOYWFzV0kKA5LIcswpe5DNYGq0s66WDVhVUcYQik9i
        Gd7MnViL1wmwEHoWe/0+XX8oXrBnJNHLN+WPghicFoqgzaf9vhXYRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T04:11:25Z"
  mac: ENC[AES256_GCM,data:xNN5Hi9cEB7PnqM3EnQFzdNCx2+/V43/1UzSQTO6jLv1bPyZKxUZe5l+kr4dABeg2y+2AcZ+vuZMld2lv/x0TreY64LMgZOqWSQPdqAUMyCmR2StkbJ0QTFF1H1ZayP9lnQUp/3FQUd6TJXxJZ/S++6BuNXOKHlwS11Srsv7zU4=,iv:t+0S0WWXSPgCTQEsUK6n5qP4cFKJVwOHak52pES7Q0M=,tag:lB31PMM6WRzoOslRUUTkSA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
